### ISSUE TITLE
Image Generation AIOE and AIIE.xlsx file contains Language Modeling AIOE

### ISSUE THREAD

**Issue by Mmichio** [AIOE-Data/AIOE#2]
Hi! Thank you for the nice work.
I am wondering you mistakenly put language score to the file for image ai exposure.
Could you check if you have time?
Thank you!

**Comment by Mmichio** [comment]
Sorry, I re-checked that the scores are different, although the label is the same.
There is no big issue for this, so I close this issue.
Thank you.

**Comment by AIOE-Data** [comment]
Thank you for flagging this issue -- yes, there was an issue with the labeling of columns. I have have updated the data to fix this.
